version: 1
formatters:
  simple:
    format: 'in file: %(filename)s  - in message: %(message)s - in function: %(funcName)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    filename: log.txt
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console]

